numbers = {
    "1": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 1,
        "row": 1,
        "align": "left",
    },
    "2": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 1,
        "row": 2,
        "align": "right",
    },
    "3": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 1,
        "row": 3,
        "align": "left",
    }, 
    "4": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 1,
        "row": 1,
        "align": "right",

    },
    "5": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 1,
        "row": 2,
        "align": "left",
        },
    "6": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 1,
        "row": 3,
        "align": "right",
    },
    "7": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 1,
        "row": 1,
        "align": "left",
    },
    "8": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 1,
        "row": 2,
        "align": "right",
    },
    "9": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 1,
        "row": 3,
        "align": "left",
    }, 
    "10": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 1,
        "row": 1,
        "align": "right",
    },
    "11": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 1,
        "row": 2,
        "align": "right",
    },
    "12": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 1,
        "row": 3,
        "align": "left",
    },
    "13": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 1,
        "align": "right",
    },
    "14": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 2,
        "row": 2,
        "align": "left",
    }, 
    "15": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 3,
        "align": "right",
    },
    "16": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 2,
        "row": 1,
        "align": "left",
    },
    "17": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 2,
        "align": "right",
    },
    "18": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 2,
        "row": 3,
        "align": "left",
    }, 
    "19": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 1,
        "align": "left",
    },
    "20": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 2,
        "row": 2,
        "align": "right",
    },
    "21": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 3,
        "align": "left",
    }, 
    "22": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 2,
        "row": 1,
        "align": "left",
    }, 
    "23": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 2,
        "align": "left",
    },
    "24": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 2,
        "row": 3,
        "align": "right",
    },
    "25": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 3,
        "row": 1,
        "align": "left",
    }, 
    "26": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 3,
        "row": 2,
        "align": "left",
    }, 
    "27": {
        "color": "red",
        "evenOdd": "odd",
        "twelve": 3,
        "row": 3,
        "align": "left",
    },
    "28": {
        "color": "black",
        "evenOdd": "even",
        "twelve": 3,
        "row": 1,
        "align": "right",
    },
    "29": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 3,
        "row": 2,
        "align": "right",
    },
    "30": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 3,
        "row": 3,
        "align": "left",
    },
    "31": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 2,
        "row": 1,
        "align": "left",
    },
    "32": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 2,
        "row": 2,
        "align": "right",
    },
    "33": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 3,
        "row": 3,
        "align": "left",
    }, 
    "34": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 3,
        "row": 1,
        "align": "left",
    }, 
    "35": {
        "color": "black",
        "evenOdd": "odd",
        "twelve": 3,
        "row": 2,
        "align": "left",
    },
    "36": {
        "color": "red",
        "evenOdd": "even",
        "twelve": 3,
        "row": 3,
        "align": "right",
    },
    
}
